### PR TITLE
Fix calling spans

### PR DESCRIPTION
**Pull request by kyleseaman**
Fixes an issue where we were always getting spans

### CODE REVIEW

**Comment by brandly** [comment]
i don't understand what's going on here. what call was faulty that's now working? does importing `Select` change any behavior?

also should we have `virtualtime` in our `requirements.txt` for python 2.7 support?

**Comment by kyleseaman** [comment]
@brandly importing `Select` allows us to remove `select()` from `sentenai.query()` -- that was a secondary discovery.  The main piece was that `.pool` was getting initialized even if we didn't need it, so it was automatically hitting `../spans`.

**Comment by xnomagichash** [comment]
@brandly Python doesn't fail when objects that aren't present are referenced from within a closure until the object is evaluated. Select() was only evaluated in the case of a select clause being absent from a query argument because python only evaluated the left-hand side of an `or` unless it evaluates to false.

RE: Virtualtime...I haven't found a way to make dual requirements for python 2.7 & 3.x. If we add it to our requirements it will always fail to pip install in 3.x because virtualtime doesn't exist as a package in 3.x (not even a dummy package). It's a really frustrating issue.

**Comment by brandly** [comment]
i [removed `datetimes` from the type tests](https://github.com/Sentenai/py-sentenai/pull/29/commits/9483cfe2725fee594a14a942d0e35ddd57a5e035) due to the `virtualtime` issues. potentially there's a better approach, but CI is passing now.

also, it appears installing `virtualtime` is no longer an issue in py3, so we generally have better py2 support now.

**Pull request merged**
